services:
  - type: web
    name: netflix
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn Netflix.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: SECRET_KEY
        sync: true
      - key: DATABASE_URL
        sync: true
      - key: DEBUG
        sync: true
